#!/usr/bin/env bash

series_name="$1"
value_name="$2"
csv_file="$3"

field() {
  echo "$1" | cut -d "," -f $2 | sed 's/"//g'
}

handle_line() {
  declare -r line="$1"
  declare -r timestamp="$(field "${line}" 2)" value="$(field "${line}" 3)" unit="$(field "${line}" 5)" measured_by="$(field "${line}" 6)" time_unit="$(field "${line}" 7)"
  timestamp_ns="${timestamp}0000000"
  echo "$series_name,measured_by=$measured_by,time_unit=$time_unit,unit=$unit $value_name=${value} ${timestamp_ns}"
}

echo "# Created on $(date "+%Y-%m-%dT%H:%M:%S%Z") based on '$csv_file'"
tail -n +1 $csv_file | while read line; do
  echo $(handle_line "$line")
done
