name: Scrape Data
on:
  workflow_dispatch: {}
  schedule:
    - cron: '27 0,12 * * *'
jobs:
  scrape:
    name: Scrape SolarEdge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Runner
        run: |
          sudo timedatectl set-timezone "Europe/Brussels"
          export SOLAREDGE_API_TOKEN="${{ secrets.SOLAREDGE_API_TOKEN }}"
          export SOLAREDGE_SITE_ID="${{ secrets.SOLAREDGE_SITE_ID }}"
          git config user.name "GitHub Bot"
          git config user.email "<>"
      - name: Scrape SolarEdge API
        run: |
          DATE=$(date "+%Y-%m-%d")
          ./archive $DATE
          git add "data/raw/$(date "+%Y/%m/%d")"
          CHANGES=$(git status -s | cut -d " " -f 3)
          if [[ -z "$CHANGES" ]]; then
            git commit -m "data: Automatic scrape 
            git push origin
          fi
