name: Scrape Data
on:
  workflow_dispatch: {}
  schedule:
    - cron: '27 0,12 * * *'
jobs:
  scrape:
    name: Scrape SolarEdge
    runs-on: ubuntu-latest
    env:
      SOLAREDGE_API_TOKEN: "${{ secrets.SOLAREDGE_API_TOKEN }}"
      SOLAREDGE_SITE_ID: "${{ secrets.SOLAREDGE_SITE_ID }}"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Runner
        run: |
          sudo timedatectl set-timezone "Europe/Brussels"
          git config user.name "GitHub Bot"
          git config user.email "<>"
      - name: Scrape SolarEdge API
        run: |
          TIME=$(date "+%Y-%m-%dT%T")
          DATE=$(date "+%Y-%m-%d" -d "$TIME")
          ./archive $DATE
          git add "data/raw/$(date "+%Y/%m/%d" -d "$TIME")"
          CHANGES=$(git status -s | cut -d " " -f 3)
          if [[ -n "$CHANGES" ]]; then
            git commit -m "data: Automatic scrape on ${TIME/T/ }"
            git push origin
          fi
